server:
  port: 10001
  tomcat:
    uri-encoding: UTF-8
#  servlet:
#    context-path: /star
# springBoot 2.4.0以上
#spring:
#  config:
#    activate:
#      on-profile:
#        #启动环境
#        pro
spring:
  application:
    name: star
  # 环境 dev|test|prod
  profiles:
    active: @profiles.active@
    include: properties
  # jackson全局时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 缓存管理器
  cache:
    type: redis
    redis:
      # 是否存入空值，防止击穿
      cache-null-values: true
      # 使用前缀，分区
      use-key-prefix: true

mybatis-flex:
  mapper-locations:
    - classpath:/mapper/*/*.xml
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-field: deleteFlag
#      # 逻辑已删除值(默认为 1)
#      logic-delete-value: 1
#      # 逻辑未删除值(默认为 0)
#      logic-not-delete-value: 0

springdoc:
  api-docs:
    enabled: @swagger.enable@
    path: /swagger/api/docs
  # 分组配置
  group-configs:
    - group: admin
      packages-to-scan: com.star.web.admin.controller
      paths-to-match: /
    - group: test
      packages-to-scan: com.star.web.test.controller
      paths-to-match: /

liteflow:
  rule-source: config/flow.el.xml
  when-max-wait-seconds: 15
  when-max-workers: 16
  when-queue-limit: 512
